import type { LevelDef } from '../../types.ts'

const level: LevelDef = {
  id: 'ch3-1',
  name: '',
  targetMolecule: '',
  explanation: '',
  moleculeName: '',
  moleculeExplanation: '',
  grid: {
    width: 9,
    height: 7,
    walls: [
      [0, 0],
      [0, 6],
      [1, 0],
      [1, 6],
      [2, 0],
      [2, 6],
      [3, 0],
      [1, 3],
      [1, 4],
      [1, 5],
      [2, 3],
      [2, 4],
      [2, 5],
      [6, 3],
      [6, 4],
      [6, 5],
      [7, 3],
      [7, 4],
      [7, 5],
      [3, 6],
      [4, 0],
      [4, 6],
      [5, 0],
      [5, 6],
      [6, 0],
      [6, 6],
      [7, 0],
      [7, 6],
      [8, 0],
      [8, 6],
      [0, 1],
      [8, 1],
      [0, 2],
      [8, 2],
      [0, 3],
      [8, 3],
      [0, 4],
      [8, 4],
      [0, 5],
      [8, 5],
    ],
  },

  atoms: [
    { id: 'H1', type: 'H', x: 2, y: 2, controlled: true },
    { id: 'H2', type: 'H', x: 4, y: 3 },
    { id: 'O1', type: 'O', x: 4, y: 5 },
    { id: 'He1', type: 'He', x: 6, y: 2 },
  ],
}

export default level
