import type { LevelDef } from '../../types.ts'

// 형식만 있는 빈 템플릿 — 아래 값 채워서 실제 레벨로 교체할 것.
const level: LevelDef = {
  id: 'ch2-2',
  name: '',
  targetMolecule: '',
  explanation: '',
  moleculeName: '',
  moleculeExplanation: '',
  grid: {
    width: 9,
    height: 10,
    walls: [
      [0, 0],
      [0, 9],
      [1, 0],
      [1, 1],
      [1, 2],
      [1, 9],
      [2, 0],
      [2, 1],
      [2, 2],
      [2, 9],
      [3, 0],
      [3, 9],
      [4, 0],
      [4, 9],
      [5, 0],
      [5, 9],
      [6, 0],
      [6, 9],
      [7, 0],
      [7, 1],
      [7, 2],
      [7, 9],
      [8, 0],
      [6, 1],
      [6, 2],
      [8, 9],
      [0, 1],
      [8, 1],
      [0, 2],
      [8, 2],
      [0, 3],
      [8, 3],
      [0, 4],
      [8, 4],
      [0, 5],
      [8, 5],
      [0, 6],
      [8, 6],
      [0, 7],
      [8, 7],
      [0, 8],
      [8, 8],
      [5, 5],
      [3, 5],
      [5, 7],
      [3, 7],
    ],
  },

  atoms: [
    { id: 'n1', type: 'N', x: 4, y: 6, controlled: true },
    { id: 'n2', type: 'N', x: 4, y: 4 },
    { id: 'h1', type: 'H', x: 2, y: 6 },
    { id: 'h2', type: 'H', x: 6, y: 6 },
    { id: 'h3', type: 'H', x: 3, y: 2 },
    { id: 'h4', type: 'H', x: 5, y: 2 },

  ],
}

export default level
